version: "3.1"
services:
  mongo:
    image: mongo
    container_name: "fallstack2024-mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker
    volumes:
      - "mongodb:/data/db"
    ports:
      - 27017:27017
volumes:
  mongodb:
